//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSC.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AspPagerRes_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AspPagerRes_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSC.Res.AspPagerRes_EN", typeof(AspPagerRes_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录总数只有一页，AspNetPager已自动隐藏，若需在只有一页数据时显示AspNetPager，请将AlwaysShow属性值设为true！.
        /// </summary>
        internal static string autohideinfo {
            get {
                return ResourceManager.GetString("autohideinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本框及提交按钮.
        /// </summary>
        internal static string cat_InputBox {
            get {
                return ResourceManager.GetString("cat_InputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导航.
        /// </summary>
        internal static string cat_Navigation {
            get {
                return ResourceManager.GetString("cat_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分页.
        /// </summary>
        internal static string cat_Paging {
            get {
                return ResourceManager.GetString("cat_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下拉选项.
        /// </summary>
        internal static string cat_Select {
            get {
                return ResourceManager.GetString("cat_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ANP_checkInput(bid,mv){var el=document.getElementById(bid);var r=new RegExp(&quot;^\\s*(\\d+)\\s*$&quot;);
        ///if(r.test(el.value)){if(RegExp.$1&lt;1||RegExp.$1&gt;mv){alert(&quot;%PageIndexOutOfRangeErrorMessage%&quot;);el.focus();el.select();return false;}
        ///return true;}alert(&quot;%InvalidPageIndexErrorMessage%&quot;);el.focus();el.select();return false;}.
        /// </summary>
        internal static string checkinputscript {
            get {
                return ResourceManager.GetString("checkinputscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控件“%controlID%”不存在或不是“Wuqi.Webdiyer.AspNetPager”类型。.
        /// </summary>
        internal static string clonefromexeption {
            get {
                return ResourceManager.GetString("clonefromexeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页索引不是有效的数值！.
        /// </summary>
        internal static string def_InvalidPIErrorMsg {
            get {
                return ResourceManager.GetString("def_InvalidPIErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转到第{0}页.
        /// </summary>
        internal static string def_NavigationToolTipTextFormatString {
            get {
                return ResourceManager.GetString("def_NavigationToolTipTextFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页索引超出范围！.
        /// </summary>
        internal static string def_PIOutOfRangerMsg {
            get {
                return ResourceManager.GetString("def_PIOutOfRangerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总是显示分页控件，即使要分页的数据只要一页.
        /// </summary>
        internal static string desc_AlwaysShow {
            get {
                return ResourceManager.GetString("desc_AlwaysShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 专用于ASP.Net Web应用程序的分页控件.
        /// </summary>
        internal static string desc_AspNetPager {
            get {
                return ResourceManager.GetString("desc_AspNetPager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定当使用图片按钮时，图片的对齐方式.
        /// </summary>
        internal static string desc_ButtonImageAlign {
            get {
                return ResourceManager.GetString("desc_ButtonImageAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当使用图片按钮时，图片的类型，如gif或jpg，该值即图片文件的后缀名.
        /// </summary>
        internal static string desc_ButtonImageExtension {
            get {
                return ResourceManager.GetString("desc_ButtonImageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义图片文件名的后缀字符串（非文件后缀名），如图片“1f.gif”的ButtonImageNameExtension即为“f”.
        /// </summary>
        internal static string desc_ButtonImageNameExtension {
            get {
                return ResourceManager.GetString("desc_ButtonImageNameExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 克隆指定的另一个AspNetPager的相关属性及事件处理程序等.
        /// </summary>
        internal static string desc_CloneFrom {
            get {
                return ResourceManager.GetString("desc_CloneFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前页索引按钮的图片名后缀字符串.
        /// </summary>
        internal static string desc_CpiButtonImageNameExtension {
            get {
                return ResourceManager.GetString("desc_CpiButtonImageNameExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用于控件的CSS类名.
        /// </summary>
        internal static string desc_CssClass {
            get {
                return ResourceManager.GetString("desc_CssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用于当前页导航按钮的CSS类名.
        /// </summary>
        internal static string desc_CurrentPageButtonClass {
            get {
                return ResourceManager.GetString("desc_CurrentPageButtonClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用于当前页导航按钮的CSS样式.
        /// </summary>
        internal static string desc_CurrentPageButtonStyle {
            get {
                return ResourceManager.GetString("desc_CurrentPageButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前页的索引.
        /// </summary>
        internal static string desc_CurrentPageIndex {
            get {
                return ResourceManager.GetString("desc_CurrentPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用于用户自定义信息区的级联样式表类名.
        /// </summary>
        internal static string desc_CustomInfoClass {
            get {
                return ResourceManager.GetString("desc_CustomInfoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要显示在用户自定义信息区的用户自定义HTML信息文本.
        /// </summary>
        internal static string desc_CustomInfoHTML {
            get {
                return ResourceManager.GetString("desc_CustomInfoHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户自定义信息区的宽度.
        /// </summary>
        internal static string desc_CustomInfoSectionWidth {
            get {
                return ResourceManager.GetString("desc_CustomInfoSectionWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用于用户自定义信息区的CSS样式文本.
        /// </summary>
        internal static string desc_CustomInfoStyle {
            get {
                return ResourceManager.GetString("desc_CustomInfoStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户自定义信息区文本的对齐方式.
        /// </summary>
        internal static string desc_CustomInfoTextAlign {
            get {
                return ResourceManager.GetString("desc_CustomInfoTextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已禁用的页导航按钮的图片名后缀字符串.
        /// </summary>
        internal static string desc_DisabledButtonImageNameExtension {
            get {
                return ResourceManager.GetString("desc_DisabledButtonImageNameExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否启用Url重写.
        /// </summary>
        internal static string desc_EnableUrlWriting {
            get {
                return ResourceManager.GetString("desc_EnableUrlWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一页按钮上显示的文本.
        /// </summary>
        internal static string desc_FirstPageText {
            get {
                return ResourceManager.GetString("desc_FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当使用图片按钮时，指定图片文件的路径.
        /// </summary>
        internal static string desc_ImagePath {
            get {
                return ResourceManager.GetString("desc_ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用于页索引输入文本框的CSS类名.
        /// </summary>
        internal static string desc_InputBoxClass {
            get {
                return ResourceManager.GetString("desc_InputBoxClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用于页索引输入文本框的CSS样式文本.
        /// </summary>
        internal static string desc_InputBoxStyle {
            get {
                return ResourceManager.GetString("desc_InputBoxStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当用户输入无效的页索引（负值或非数字）时在客户端显示的错误信息。.
        /// </summary>
        internal static string desc_InvalidPIErrorMsg {
            get {
                return ResourceManager.GetString("desc_InvalidPIErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最后一页按钮上显示的文本.
        /// </summary>
        internal static string desc_LastPageText {
            get {
                return ResourceManager.GetString("desc_LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “更多页”（...）按钮的类型.
        /// </summary>
        internal static string desc_MoreButtonType {
            get {
                return ResourceManager.GetString("desc_MoreButtonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一页、上一页、下一页和最后一页按钮的类型.
        /// </summary>
        internal static string desc_NavigationButtonType {
            get {
                return ResourceManager.GetString("desc_NavigationButtonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分页导航按钮上显示的提示文本的格式.
        /// </summary>
        internal static string desc_NavigationToolTipTextFormatString {
            get {
                return ResourceManager.GetString("desc_NavigationToolTipTextFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页索引数值按钮上文字的显示格式.
        /// </summary>
        internal static string desc_NBTFormatString {
            get {
                return ResourceManager.GetString("desc_NBTFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页按钮上显示的文本.
        /// </summary>
        internal static string desc_NextPageText {
            get {
                return ResourceManager.GetString("desc_NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要显示的页索引数值按钮的数目.
        /// </summary>
        internal static string desc_NumericButtonCount {
            get {
                return ResourceManager.GetString("desc_NumericButtonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页导航数值按钮的类型.
        /// </summary>
        internal static string desc_NumericButtonType {
            get {
                return ResourceManager.GetString("desc_NumericButtonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每页显示的记录数.
        /// </summary>
        internal static string desc_PageSize {
            get {
                return ResourceManager.GetString("desc_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分页导航按钮之间的间距.
        /// </summary>
        internal static string desc_PagingButtonSpacing {
            get {
                return ResourceManager.GetString("desc_PagingButtonSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分页导航按钮的类型，是使用文字还是图片.
        /// </summary>
        internal static string desc_PagingButtonType {
            get {
                return ResourceManager.GetString("desc_PagingButtonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当用户输入的页索引超出范围（大于最大页索引或小于最小页索引）时在客户端显示的错误信息。.
        /// </summary>
        internal static string desc_PIOutOfRangeMsg {
            get {
                return ResourceManager.GetString("desc_PIOutOfRangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页按钮上显示的文本.
        /// </summary>
        internal static string desc_PrevPageText {
            get {
                return ResourceManager.GetString("desc_PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要分页的所有记录的总数，该值须在程序运行时设置，默认值为225是为设计时支持而设置的参照值。.
        /// </summary>
        internal static string desc_RecordCount {
            get {
                return ResourceManager.GetString("desc_RecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定当ShowInputBox设为ShowInputBox.Auto时，当总页数达到多少时才显示页索引输入文本框.
        /// </summary>
        internal static string desc_ShowBoxThreshold {
            get {
                return ResourceManager.GetString("desc_ShowBoxThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示当前页和总页数信息，默认值为不显示，值为ShowCustomInfoSection.Left时将显示在页索引前，为ShowCustomInfoSection.Right时将显示在页索引后.
        /// </summary>
        internal static string desc_ShowCustomInfoSection {
            get {
                return ResourceManager.GetString("desc_ShowCustomInfoSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示已禁用的按钮.
        /// </summary>
        internal static string desc_ShowDisabledButtons {
            get {
                return ResourceManager.GetString("desc_ShowDisabledButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否在页导航元素中显示第一页和最后一页按钮.
        /// </summary>
        internal static string desc_ShowFirstLast {
            get {
                return ResourceManager.GetString("desc_ShowFirstLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定页索引文本框的显示方式.
        /// </summary>
        internal static string desc_ShowInputBox {
            get {
                return ResourceManager.GetString("desc_ShowInputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定当鼠标停留在导航按钮上时，是否显示工具提示.
        /// </summary>
        internal static string desc_ShowNavigationToolTip {
            get {
                return ResourceManager.GetString("desc_ShowNavigationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否在页导航元素中显示数值按钮.
        /// </summary>
        internal static string desc_ShowPageIndex {
            get {
                return ResourceManager.GetString("desc_ShowPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示下拉页.
        /// </summary>
        internal static string desc_ShowPagerSelect {
            get {
                return ResourceManager.GetString("desc_ShowPagerSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否在页导航元素中显示上一页和下一页按钮.
        /// </summary>
        internal static string desc_ShowPrevNext {
            get {
                return ResourceManager.GetString("desc_ShowPrevNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用于提交按钮的CSS类名.
        /// </summary>
        internal static string desc_SubmitButtonClass {
            get {
                return ResourceManager.GetString("desc_SubmitButtonClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用于提交按钮的CSS样式.
        /// </summary>
        internal static string desc_SubmitButtonStyle {
            get {
                return ResourceManager.GetString("desc_SubmitButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交按钮上的文本.
        /// </summary>
        internal static string desc_SubmitButtonText {
            get {
                return ResourceManager.GetString("desc_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页索引输入文本框后的文本内容字符串.
        /// </summary>
        internal static string desc_TextAfterInputBox {
            get {
                return ResourceManager.GetString("desc_TextAfterInputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页索引输入文本框前的文本内容字符串.
        /// </summary>
        internal static string desc_TextBeforeInputBox {
            get {
                return ResourceManager.GetString("desc_TextBeforeInputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当启用Url分页方式时，显示在url中表示要传递的页索引的参数的名称.
        /// </summary>
        internal static string desc_UrlPageIndexName {
            get {
                return ResourceManager.GetString("desc_UrlPageIndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否使用url传递分页信息的方式来分页.
        /// </summary>
        internal static string desc_UrlPaging {
            get {
                return ResourceManager.GetString("desc_UrlPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url重写格式.
        /// </summary>
        internal static string desc_UrlRewritePattern {
            get {
                return ResourceManager.GetString("desc_UrlRewritePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every page.
        /// </summary>
        internal static string EveryPage {
            get {
                return ResourceManager.GetString("EveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Go to.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ANP_keydown(e,btnId){
        ///var kcode;
        ///if(window.event){kcode=e.keyCode;}
        ///else if(e.which){kcode=e.which;}
        ///var validKey=(kcode==8||kcode==46||kcode==37||kcode==39||(kcode&gt;=48&amp;&amp;kcode&lt;=57)||(kcode&gt;=96&amp;&amp;kcode&lt;=105));
        ///if(!validKey){
        ///if(kcode==13) document.getElementById(btnId).click();
        ///if(e.preventDefault) e.preventDefault();else{event.returnValue=false};
        ///}
        ///}.
        /// </summary>
        internal static string keydownscript {
            get {
                return ResourceManager.GetString("keydownscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的CloneFrom属性值，AspNetPager控件不能被递归克隆.
        /// </summary>
        internal static string recusiveclonefrom {
            get {
                return ResourceManager.GetString("recusiveclonefrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
