//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSC.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CultureRes_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CultureRes_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSC.Res.CultureRes_EN", typeof(CultureRes_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string CAP_BTN_ADD {
            get {
                return ResourceManager.GetString("CAP_BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CAP_BTN_CLOSE {
            get {
                return ResourceManager.GetString("CAP_BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string CAP_BTN_COLLAPSE {
            get {
                return ResourceManager.GetString("CAP_BTN_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CAP_BTN_DELETE {
            get {
                return ResourceManager.GetString("CAP_BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        internal static string CAP_BTN_DELETE_FILE {
            get {
                return ResourceManager.GetString("CAP_BTN_DELETE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string CAP_BTN_EXPAND {
            get {
                return ResourceManager.GetString("CAP_BTN_EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CAP_BTN_FINISH {
            get {
                return ResourceManager.GetString("CAP_BTN_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        internal static string CAP_BTN_GETPASSWORD {
            get {
                return ResourceManager.GetString("CAP_BTN_GETPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string CAP_BTN_LOGIN {
            get {
                return ResourceManager.GetString("CAP_BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CAP_BTN_OK {
            get {
                return ResourceManager.GetString("CAP_BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string CAP_BTN_QUERY {
            get {
                return ResourceManager.GetString("CAP_BTN_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query all.
        /// </summary>
        internal static string CAP_BTN_QUERYALL {
            get {
                return ResourceManager.GetString("CAP_BTN_QUERYALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string CAP_BTN_REFRESH {
            get {
                return ResourceManager.GetString("CAP_BTN_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repaire.
        /// </summary>
        internal static string CAP_BTN_REPAIRE {
            get {
                return ResourceManager.GetString("CAP_BTN_REPAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CAP_BTN_SAVE {
            get {
                return ResourceManager.GetString("CAP_BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string CAP_BTN_SEARCH {
            get {
                return ResourceManager.GetString("CAP_BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        internal static string CAP_BTN_SYS_ADMIN_CLEAN {
            get {
                return ResourceManager.GetString("CAP_BTN_SYS_ADMIN_CLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string CAP_BTN_SYS_ADMIN_SYNC_STATUS {
            get {
                return ResourceManager.GetString("CAP_BTN_SYS_ADMIN_SYNC_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string CAP_BTN_UPLOAD {
            get {
                return ResourceManager.GetString("CAP_BTN_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string CAP_BTN_VALIDATE {
            get {
                return ResourceManager.GetString("CAP_BTN_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Check.
        /// </summary>
        internal static string CAP_CHECKBOX_AUTHORITY {
            get {
                return ResourceManager.GetString("CAP_CHECKBOX_AUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string CAP_LBL_ACTIVE {
            get {
                return ResourceManager.GetString("CAP_LBL_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string CAP_LBL_ADDRESS {
            get {
                return ResourceManager.GetString("CAP_LBL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Department.
        /// </summary>
        internal static string CAP_LBL_BY_DEPT {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Module.
        /// </summary>
        internal static string CAP_LBL_BY_MOD {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Role.
        /// </summary>
        internal static string CAP_LBL_BY_ROLE {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Site.
        /// </summary>
        internal static string CAP_LBL_BY_SITE {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By User.
        /// </summary>
        internal static string CAP_LBL_BY_USER {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Authority.
        /// </summary>
        internal static string CAP_LBL_CHECK_AUTHORITY {
            get {
                return ResourceManager.GetString("CAP_LBL_CHECK_AUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string CAP_LBL_DEPT {
            get {
                return ResourceManager.GetString("CAP_LBL_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept.
        /// </summary>
        internal static string CAP_LBL_DEPT_CODE {
            get {
                return ResourceManager.GetString("CAP_LBL_DEPT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CAP_LBL_DESC {
            get {
                return ResourceManager.GetString("CAP_LBL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display style.
        /// </summary>
        internal static string CAP_LBL_DISP_STYLE {
            get {
                return ResourceManager.GetString("CAP_LBL_DISP_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string CAP_LBL_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp Id.
        /// </summary>
        internal static string CAP_LBL_EMP_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_EMP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp Name.
        /// </summary>
        internal static string CAP_LBL_EMP_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_EMP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp No..
        /// </summary>
        internal static string CAP_LBL_EMP_NO {
            get {
                return ResourceManager.GetString("CAP_LBL_EMP_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        internal static string CAP_LBL_ENTRY_DATE {
            get {
                return ResourceManager.GetString("CAP_LBL_ENTRY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext..
        /// </summary>
        internal static string CAP_LBL_EXT {
            get {
                return ResourceManager.GetString("CAP_LBL_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext No.
        /// </summary>
        internal static string CAP_LBL_EXT_NO {
            get {
                return ResourceManager.GetString("CAP_LBL_EXT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string CAP_LBL_FILE_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function ID.
        /// </summary>
        internal static string CAP_LBL_FUNC_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_FUNC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P--Pop up new window.
        /// </summary>
        internal static string CAP_LBL_HEADLINK_PUPOP {
            get {
                return ResourceManager.GetString("CAP_LBL_HEADLINK_PUPOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L--Self window.
        /// </summary>
        internal static string CAP_LBL_HEADLINK_SELF {
            get {
                return ResourceManager.GetString("CAP_LBL_HEADLINK_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys.Protected.
        /// </summary>
        internal static string CAP_LBL_IS_SYS {
            get {
                return ResourceManager.GetString("CAP_LBL_IS_SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Desc.
        /// </summary>
        internal static string CAP_LBL_JOB_DESC {
            get {
                return ResourceManager.GetString("CAP_LBL_JOB_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string CAP_LBL_KEY {
            get {
                return ResourceManager.GetString("CAP_LBL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Type.
        /// </summary>
        internal static string CAP_LBL_LINKTYPE {
            get {
                return ResourceManager.GetString("CAP_LBL_LINKTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        internal static string CAP_LBL_LOGIN_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_LOGIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string CAP_LBL_MAIL_ACCOUNT {
            get {
                return ResourceManager.GetString("CAP_LBL_MAIL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string CAP_LBL_MODULE {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module ID.
        /// </summary>
        internal static string CAP_LBL_MODULE_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string CAP_LBL_MODULE_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name SC.
        /// </summary>
        internal static string CAP_LBL_MODULE_NAME_SC {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE_NAME_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name TC.
        /// </summary>
        internal static string CAP_LBL_MODULE_NAME_TC {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE_NAME_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CAP_LBL_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left navigation.
        /// </summary>
        internal static string CAP_LBL_NAVIGATING {
            get {
                return ResourceManager.GetString("CAP_LBL_NAVIGATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string CAP_LBL_ORDER {
            get {
                return ResourceManager.GetString("CAP_LBL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        internal static string CAP_LBL_PARENT_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_PARENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Module.
        /// </summary>
        internal static string CAP_LBL_PARENT_MODULE {
            get {
                return ResourceManager.GetString("CAP_LBL_PARENT_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        internal static string CAP_LBL_PARENT_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_PARENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CAP_LBL_PASS_WORD {
            get {
                return ResourceManager.GetString("CAP_LBL_PASS_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CAP_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("CAP_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CAP_LBL_RESULT {
            get {
                return ResourceManager.GetString("CAP_LBL_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string CAP_LBL_ROLE {
            get {
                return ResourceManager.GetString("CAP_LBL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID.
        /// </summary>
        internal static string CAP_LBL_ROLE_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_ROLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string CAP_LBL_ROLE_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string CAP_LBL_SITE {
            get {
                return ResourceManager.GetString("CAP_LBL_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string CAP_LBL_SITE_CODE {
            get {
                return ResourceManager.GetString("CAP_LBL_SITE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Sys ID.
        /// </summary>
        internal static string CAP_LBL_SUB_SYS_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_SUB_SYS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up the rubbish forms of NPM .
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_CLEAN_FORM {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_CLEAN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of INV forms and FlowER forms.
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_SYNC_INV {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_SYNC_INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of Item No forms and FlowER forms.
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_SYNC_ITEM {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_SYNC_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Status of PACN forms and FlowER forms.
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_SYNC_PACN {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_SYNC_PACN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Status synchronization.
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_SYNC_STATUS {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_SYNC_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse file.
        /// </summary>
        internal static string CAP_LBL_UPLOAD_BROWSE {
            get {
                return ResourceManager.GetString("CAP_LBL_UPLOAD_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string CAP_LBL_UPLOAD_TIME {
            get {
                return ResourceManager.GetString("CAP_LBL_UPLOAD_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader.
        /// </summary>
        internal static string CAP_LBL_UPLOADER {
            get {
                return ResourceManager.GetString("CAP_LBL_UPLOADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string CAP_LBL_USER {
            get {
                return ResourceManager.GetString("CAP_LBL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string CAP_LBL_USER_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string CAP_LBL_VALUE {
            get {
                return ResourceManager.GetString("CAP_LBL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string CAP_TTL_ACTIVE {
            get {
                return ResourceManager.GetString("CAP_TTL_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security--&gt;Department security setup.
        /// </summary>
        internal static string CAP_TTL_DEPT_MODULE {
            get {
                return ResourceManager.GetString("CAP_TTL_DEPT_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module&apos;s Function setup.
        /// </summary>
        internal static string CAP_TTL_FUNC {
            get {
                return ResourceManager.GetString("CAP_TTL_FUNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header menu link .
        /// </summary>
        internal static string CAP_TTL_HEADLINK {
            get {
                return ResourceManager.GetString("CAP_TTL_HEADLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Header link.
        /// </summary>
        internal static string CAP_TTL_HEADLINK_EDIT {
            get {
                return ResourceManager.GetString("CAP_TTL_HEADLINK_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left navigation setup.
        /// </summary>
        internal static string CAP_TTL_LEFTMENU {
            get {
                return ResourceManager.GetString("CAP_TTL_LEFTMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Navigation menu Item.
        /// </summary>
        internal static string CAP_TTL_LEFTMENU_EDIT {
            get {
                return ResourceManager.GetString("CAP_TTL_LEFTMENU_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter setup.
        /// </summary>
        internal static string CAP_TTL_PARA {
            get {
                return ResourceManager.GetString("CAP_TTL_PARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Edit Parameter.
        /// </summary>
        internal static string CAP_TTL_PARA_EDIT {
            get {
                return ResourceManager.GetString("CAP_TTL_PARA_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security--&gt;Security Query.
        /// </summary>
        internal static string CAP_TTL_PMT_QRY {
            get {
                return ResourceManager.GetString("CAP_TTL_PMT_QRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security--&gt;Role Maintanance.
        /// </summary>
        internal static string CAP_TTL_ROLE {
            get {
                return ResourceManager.GetString("CAP_TTL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security--&gt;Role-Department setup.
        /// </summary>
        internal static string CAP_TTL_ROLE_DEPT {
            get {
                return ResourceManager.GetString("CAP_TTL_ROLE_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security--&gt;Role security setup.
        /// </summary>
        internal static string CAP_TTL_ROLE_MODULE {
            get {
                return ResourceManager.GetString("CAP_TTL_ROLE_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security--&gt;Role-User setup.
        /// </summary>
        internal static string CAP_TTL_ROLE_USER {
            get {
                return ResourceManager.GetString("CAP_TTL_ROLE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulating User .
        /// </summary>
        internal static string CAP_TTL_SIMULATE_USER {
            get {
                return ResourceManager.GetString("CAP_TTL_SIMULATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security--&gt;Site security setup.
        /// </summary>
        internal static string CAP_TTL_SITE_MODULE {
            get {
                return ResourceManager.GetString("CAP_TTL_SITE_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPM Management tool.
        /// </summary>
        internal static string CAP_TTL_SYS_ADMIN {
            get {
                return ResourceManager.GetString("CAP_TTL_SYS_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        internal static string CAP_TTL_UPLOAD {
            get {
                return ResourceManager.GetString("CAP_TTL_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y--Active.
        /// </summary>
        internal static string CAP_TTL_USER_ACTIVE {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Maintain Edit.
        /// </summary>
        internal static string CAP_TTL_USER_EDIT {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N--Inactive.
        /// </summary>
        internal static string CAP_TTL_USER_INACTIVE {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Maintain.
        /// </summary>
        internal static string CAP_TTL_USER_MAINTAIN {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_MAINTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security--&gt;User security setup.
        /// </summary>
        internal static string CAP_TTL_USER_MODULE {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        internal static string CAP_TTL_USERSELECTOR {
            get {
                return ResourceManager.GetString("CAP_TTL_USERSELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating system configuration.
        /// </summary>
        internal static string CAP_TTL_VALIDATECFG {
            get {
                return ResourceManager.GetString("CAP_TTL_VALIDATECFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to access this page。.
        /// </summary>
        internal static string MSG_ERR_ACCESS_PAGE {
            get {
                return ResourceManager.GetString("MSG_ERR_ACCESS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to add new..
        /// </summary>
        internal static string MSG_ERR_ADD {
            get {
                return ResourceManager.GetString("MSG_ERR_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to build security control tree!.
        /// </summary>
        internal static string MSG_ERR_BUILDTREE {
            get {
                return ResourceManager.GetString("MSG_ERR_BUILDTREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete .
        /// </summary>
        internal static string MSG_ERR_CANT_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_CANT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not edit.
        /// </summary>
        internal static string MSG_ERR_CANT_EDIT {
            get {
                return ResourceManager.GetString("MSG_ERR_CANT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent can not be itself.\\r\\nThe module Parent ID you selected can not be same as its self ID..
        /// </summary>
        internal static string MSG_ERR_CANT_SAMEAS {
            get {
                return ResourceManager.GetString("MSG_ERR_CANT_SAMEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module ID you just keyed in can not be same as system name..
        /// </summary>
        internal static string MSG_ERR_CANT_SAMEAS_SYSTEM {
            get {
                return ResourceManager.GetString("MSG_ERR_CANT_SAMEAS_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect system configuration, Description: SYSTEM_ID can not be found in web.config!.
        /// </summary>
        internal static string MSG_ERR_CFG_SYSID {
            get {
                return ResourceManager.GetString("MSG_ERR_CFG_SYSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your user name and password, try again..
        /// </summary>
        internal static string MSG_ERR_CHECK_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_ERR_CHECK_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during executing SQL statement!  \\r\\n\\r\\nDesc: .
        /// </summary>
        internal static string MSG_ERR_DB_EXEC {
            get {
                return ResourceManager.GetString("MSG_ERR_DB_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to delete..
        /// </summary>
        internal static string MSG_ERR_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected items and its sub-items have been deleted successfully!.
        /// </summary>
        internal static string MSG_ERR_DELETE_ALL_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE_ALL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the selected items..
        /// </summary>
        internal static string MSG_ERR_DELETE_FAILED {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any item can be deleted..
        /// </summary>
        internal static string MSG_ERR_DELETE_NO_ITEM {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE_NO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected items have been deleted successfully!.
        /// </summary>
        internal static string MSG_ERR_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: .
        /// </summary>
        internal static string MSG_ERR_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the web address!!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_ADDRESS {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the configuration name!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_CFG_NAME {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_CFG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the configuration value!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_CFG_VALUE {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_CFG_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the department!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_DEPT {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the display name!!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_DISP_NAME {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_DISP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Module name!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_MOD {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the order!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_ORDER {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the parent Module name!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_PMOD {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_PMOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill/select the role!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_ROLE {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Sub Sys ID!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_SUBSYS {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_SUBSYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill/select the user!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_USER {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Module ID!.
        /// </summary>
        internal static string MSG_ERR_FLILLIN_MODID {
            get {
                return ResourceManager.GetString("MSG_ERR_FLILLIN_MODID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to delete the form in FlowER!.
        /// </summary>
        internal static string MSG_ERR_FLOWER_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to delete the form in FlowER!.
        /// </summary>
        internal static string MSG_ERR_FLOWER_DELFORM {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_DELFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to send the form to FlowER..
        /// </summary>
        internal static string MSG_ERR_FLOWER_SEND_FAIL {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_SEND_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to send the form to FlowER!.
        /// </summary>
        internal static string MSG_ERR_FLOWER_SENDFORM {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_SENDFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the function,\\r\\nDescription: .
        /// </summary>
        internal static string MSG_ERR_FUNC_FAIL_DEL_FUNC {
            get {
                return ResourceManager.GetString("MSG_ERR_FUNC_FAIL_DEL_FUNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the role,\\r\\nDescription: .
        /// </summary>
        internal static string MSG_ERR_FUNC_FAIL_DEL_ROLE {
            get {
                return ResourceManager.GetString("MSG_ERR_FUNC_FAIL_DEL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionID and Name can not be empty value..
        /// </summary>
        internal static string MSG_ERR_FUNC_ID_NAME_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_FUNC_ID_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to retrieve the ignored items ID!.
        /// </summary>
        internal static string MSG_ERR_GET_SUBITEM {
            get {
                return ResourceManager.GetString("MSG_ERR_GET_SUBITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the IE browser is upgraded to ver 6.0 or later..
        /// </summary>
        internal static string MSG_ERR_IE_VER {
            get {
                return ResourceManager.GetString("MSG_ERR_IE_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link does not exist in the database..
        /// </summary>
        internal static string MSG_ERR_LINK_EXISTED {
            get {
                return ResourceManager.GetString("MSG_ERR_LINK_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link has already existed in the database..
        /// </summary>
        internal static string MSG_ERR_LINK_NOTEXISTED {
            get {
                return ResourceManager.GetString("MSG_ERR_LINK_NOTEXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to log the action to file!.
        /// </summary>
        internal static string MSG_ERR_LOG {
            get {
                return ResourceManager.GetString("MSG_ERR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login name does not exist in the database..
        /// </summary>
        internal static string MSG_ERR_LOGINNAM_NOTEXISTED {
            get {
                return ResourceManager.GetString("MSG_ERR_LOGINNAM_NOTEXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name can not be empty value..
        /// </summary>
        internal static string MSG_ERR_LOGINNAME_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_LOGINNAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login name has already existed in the database..
        /// </summary>
        internal static string MSG_ERR_LOGINNAME_EXISTED {
            get {
                return ResourceManager.GetString("MSG_ERR_LOGINNAME_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:  CONTENT can not be empty..
        /// </summary>
        internal static string MSG_ERR_MAIL_ADD_CONTENT {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_ADD_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: RECEIVER can not be empty..
        /// </summary>
        internal static string MSG_ERR_MAIL_ADD_RECEIVER {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_ADD_RECEIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: SUBJECT  can not be empty..
        /// </summary>
        internal static string MSG_ERR_MAIL_ADD_SUBJECT {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_ADD_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail service configuration is incorrect!.
        /// </summary>
        internal static string MSG_ERR_MAIL_CONN_SEND {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_CONN_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail can not be empty value..
        /// </summary>
        internal static string MSG_ERR_MAIL_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to create template file for mail service!.
        /// </summary>
        internal static string MSG_ERR_MAIL_TEMPLATE {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu type can&apos;t be empty value!.
        /// </summary>
        internal static string MSG_ERR_MENUTYPE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_MENUTYPE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module ID you keyed in value can not be same as system name.
        /// </summary>
        internal static string MSG_ERR_MOD_SAMEAS_SYS {
            get {
                return ResourceManager.GetString("MSG_ERR_MOD_SAMEAS_SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have no access permission to visit this page!.
        /// </summary>
        internal static string MSG_ERR_NORIGHT {
            get {
                return ResourceManager.GetString("MSG_ERR_NORIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate the control,not defined..
        /// </summary>
        internal static string MSG_ERR_PAGER_NO_CTRL {
            get {
                return ResourceManager.GetString("MSG_ERR_PAGER_NO_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can not be empty value..
        /// </summary>
        internal static string MSG_ERR_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        internal static string MSG_ERR_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("MSG_ERR_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to retrieve your password..
        /// </summary>
        internal static string MSG_ERR_PASSWORD_RTV {
            get {
                return ResourceManager.GetString("MSG_ERR_PASSWORD_RTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find this property.
        /// </summary>
        internal static string MSG_ERR_PROPERTY_NOTFOUND {
            get {
                return ResourceManager.GetString("MSG_ERR_PROPERTY_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not edit the system protected item..
        /// </summary>
        internal static string MSG_ERR_PROTECTED_ITEM {
            get {
                return ResourceManager.GetString("MSG_ERR_PROTECTED_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create report..
        /// </summary>
        internal static string MSG_ERR_REPORT_CREATE {
            get {
                return ResourceManager.GetString("MSG_ERR_REPORT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to retrieve report parameters.
        /// </summary>
        internal static string MSG_ERR_REPORT_PARAM_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_REPORT_PARAM_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the single quotation marks from the value you inputed..
        /// </summary>
        internal static string MSG_ERR_RMV_QUOTO {
            get {
                return ResourceManager.GetString("MSG_ERR_RMV_QUOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID and Role Name can not be empty value..
        /// </summary>
        internal static string MSG_ERR_ROLE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_ROLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been saved successfully!.
        /// </summary>
        internal static string MSG_ERR_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to set the cokkie..
        /// </summary>
        internal static string MSG_ERR_SET_CK {
            get {
                return ResourceManager.GetString("MSG_ERR_SET_CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting has already existed in the database..
        /// </summary>
        internal static string MSG_ERR_SETTING_EXIST {
            get {
                return ResourceManager.GetString("MSG_ERR_SETTING_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting does not exist in the database..
        /// </summary>
        internal static string MSG_ERR_SETTING_NOTEXIST {
            get {
                return ResourceManager.GetString("MSG_ERR_SETTING_NOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMS switch is off, you can not send short message!.
        /// </summary>
        internal static string MSG_ERR_SMS_SIWTCH_OFF {
            get {
                return ResourceManager.GetString("MSG_ERR_SMS_SIWTCH_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to update..
        /// </summary>
        internal static string MSG_ERR_UPDATE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to upload a file!.
        /// </summary>
        internal static string MSG_ERR_UPLOAD {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Parameter p_intSEQ can not be zero value..
        /// </summary>
        internal static string MSG_ERR_UPLOAD_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files have been deleted!.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in uploading: .
        /// </summary>
        internal static string MSG_ERR_UPLOAD_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload file..
        /// </summary>
        internal static string MSG_ERR_UPLOAD_FAIL {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is limited to a 40MB file..
        /// </summary>
        internal static string MSG_ERR_UPLOAD_FILELMT {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_FILELMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to generate attachment html code..
        /// </summary>
        internal static string MSG_ERR_UPLOAD_GENHTML {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_GENHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not locate the file path..
        /// </summary>
        internal static string MSG_ERR_UPLOAD_LACATE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_LACATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file can be uploaded!.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_NOFILE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_NOFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type and ID found, you can not upload any file..
        /// </summary>
        internal static string MSG_ERR_UPLOAD_NOTYPE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_NOTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded successfully!.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to delete User account. \\r\\nDescription: .
        /// </summary>
        internal static string MSG_ERR_USER_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name can not be empty value..
        /// </summary>
        internal static string MSG_ERR_USER_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters can not be empty value!.
        /// </summary>
        internal static string MSG_ERR_VALUE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_VALUE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to analyze the XML package..
        /// </summary>
        internal static string MSG_ERR_XML_FORMAT {
            get {
                return ResourceManager.GetString("MSG_ERR_XML_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FlowER Account to log in..
        /// </summary>
        internal static string MSG_TIP_ACTLOGIN {
            get {
                return ResourceManager.GetString("MSG_TIP_ACTLOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Language option to change the Language..
        /// </summary>
        internal static string MSG_TIP_CHGLANG {
            get {
                return ResourceManager.GetString("MSG_TIP_CHGLANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the selected item(s)?.
        /// </summary>
        internal static string MSG_TIP_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_TIP_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling ....
        /// </summary>
        internal static string MSG_TIP_DIV_CANCELLING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_CANCELLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting ....
        /// </summary>
        internal static string MSG_TIP_DIV_DELETING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_DELETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string MSG_TIP_DIV_LOADING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing ....
        /// </summary>
        internal static string MSG_TIP_DIV_PROCESSING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving ....
        /// </summary>
        internal static string MSG_TIP_DIV_SAVING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ....
        /// </summary>
        internal static string MSG_TIP_DIV_WORKING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        internal static string MSG_TIP_FIRST_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_FIRST_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve your FlowER password to your mailbox.
        /// </summary>
        internal static string MSG_TIP_GET_PWD {
            get {
                return ResourceManager.GetString("MSG_TIP_GET_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto the page.
        /// </summary>
        internal static string MSG_TIP_GOTO_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_GOTO_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        internal static string MSG_TIP_HELLO {
            get {
                return ResourceManager.GetString("MSG_TIP_HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HitCount:.
        /// </summary>
        internal static string MSG_TIP_HITCOUNT {
            get {
                return ResourceManager.GetString("MSG_TIP_HITCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        internal static string MSG_TIP_LAST_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_LAST_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        internal static string MSG_TIP_NEXT_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_NEXT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page number/Total pages.
        /// </summary>
        internal static string MSG_TIP_PAGE_TIP {
            get {
                return ResourceManager.GetString("MSG_TIP_PAGE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string MSG_TIP_PAGER_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_PAGER_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of records to display on a page.
        /// </summary>
        internal static string MSG_TIP_PAGER_REC_PER_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_PAGER_REC_PER_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been sent to your mailbox..
        /// </summary>
        internal static string MSG_TIP_PASSWORD_MAIL {
            get {
                return ResourceManager.GetString("MSG_TIP_PASSWORD_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        internal static string MSG_TIP_PREV_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_PREV_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows account to refresh system.
        /// </summary>
        internal static string MSG_TIP_REFRESH {
            get {
                return ResourceManager.GetString("MSG_TIP_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips: .
        /// </summary>
        internal static string MSG_TIP_TIPS {
            get {
                return ResourceManager.GetString("MSG_TIP_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Record : {0}.
        /// </summary>
        internal static string MSG_TIP_TOTAL_RECORD {
            get {
                return ResourceManager.GetString("MSG_TIP_TOTAL_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips: You may keyin the department code or login name to search the data..
        /// </summary>
        internal static string MSG_TIP_USER_SELECTOR {
            get {
                return ResourceManager.GetString("MSG_TIP_USER_SELECTOR", resourceCulture);
            }
        }
    }
}
