//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSC.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CultureRes_TC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CultureRes_TC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSC.Res.CultureRes_TC", typeof(CultureRes_TC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        internal static string CAP_BTN_ADD {
            get {
                return ResourceManager.GetString("CAP_BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string CAP_BTN_CLOSE {
            get {
                return ResourceManager.GetString("CAP_BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收起.
        /// </summary>
        internal static string CAP_BTN_COLLAPSE {
            get {
                return ResourceManager.GetString("CAP_BTN_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string CAP_BTN_DELETE {
            get {
                return ResourceManager.GetString("CAP_BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除附件.
        /// </summary>
        internal static string CAP_BTN_DELETE_FILE {
            get {
                return ResourceManager.GetString("CAP_BTN_DELETE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展开.
        /// </summary>
        internal static string CAP_BTN_EXPAND {
            get {
                return ResourceManager.GetString("CAP_BTN_EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        internal static string CAP_BTN_FINISH {
            get {
                return ResourceManager.GetString("CAP_BTN_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记密码.
        /// </summary>
        internal static string CAP_BTN_GETPASSWORD {
            get {
                return ResourceManager.GetString("CAP_BTN_GETPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string CAP_BTN_LOGIN {
            get {
                return ResourceManager.GetString("CAP_BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string CAP_BTN_OK {
            get {
                return ResourceManager.GetString("CAP_BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        internal static string CAP_BTN_QUERY {
            get {
                return ResourceManager.GetString("CAP_BTN_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询所有.
        /// </summary>
        internal static string CAP_BTN_QUERYALL {
            get {
                return ResourceManager.GetString("CAP_BTN_QUERYALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        internal static string CAP_BTN_REFRESH {
            get {
                return ResourceManager.GetString("CAP_BTN_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修复.
        /// </summary>
        internal static string CAP_BTN_REPAIRE {
            get {
                return ResourceManager.GetString("CAP_BTN_REPAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string CAP_BTN_SAVE {
            get {
                return ResourceManager.GetString("CAP_BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找.
        /// </summary>
        internal static string CAP_BTN_SEARCH {
            get {
                return ResourceManager.GetString("CAP_BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清理.
        /// </summary>
        internal static string CAP_BTN_SYS_ADMIN_CLEAN {
            get {
                return ResourceManager.GetString("CAP_BTN_SYS_ADMIN_CLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步状态.
        /// </summary>
        internal static string CAP_BTN_SYS_ADMIN_SYNC_STATUS {
            get {
                return ResourceManager.GetString("CAP_BTN_SYS_ADMIN_SYNC_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附加.
        /// </summary>
        internal static string CAP_BTN_UPLOAD {
            get {
                return ResourceManager.GetString("CAP_BTN_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证.
        /// </summary>
        internal static string CAP_BTN_VALIDATE {
            get {
                return ResourceManager.GetString("CAP_BTN_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動驗證.
        /// </summary>
        internal static string CAP_CHECKBOX_AUTHORITY {
            get {
                return ResourceManager.GetString("CAP_CHECKBOX_AUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否有效.
        /// </summary>
        internal static string CAP_LBL_ACTIVE {
            get {
                return ResourceManager.GetString("CAP_LBL_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网址.
        /// </summary>
        internal static string CAP_LBL_ADDRESS {
            get {
                return ResourceManager.GetString("CAP_LBL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父结点-部门.
        /// </summary>
        internal static string CAP_LBL_BY_DEPT {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父结点-模块.
        /// </summary>
        internal static string CAP_LBL_BY_MOD {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父结点-角色.
        /// </summary>
        internal static string CAP_LBL_BY_ROLE {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父結點-Site.
        /// </summary>
        internal static string CAP_LBL_BY_SITE {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父结点-用户.
        /// </summary>
        internal static string CAP_LBL_BY_USER {
            get {
                return ResourceManager.GetString("CAP_LBL_BY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜單權限.
        /// </summary>
        internal static string CAP_LBL_CHECK_AUTHORITY {
            get {
                return ResourceManager.GetString("CAP_LBL_CHECK_AUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门.
        /// </summary>
        internal static string CAP_LBL_DEPT {
            get {
                return ResourceManager.GetString("CAP_LBL_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门.
        /// </summary>
        internal static string CAP_LBL_DEPT_CODE {
            get {
                return ResourceManager.GetString("CAP_LBL_DEPT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        internal static string CAP_LBL_DESC {
            get {
                return ResourceManager.GetString("CAP_LBL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示方式.
        /// </summary>
        internal static string CAP_LBL_DISP_STYLE {
            get {
                return ResourceManager.GetString("CAP_LBL_DISP_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示名.
        /// </summary>
        internal static string CAP_LBL_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 员工ID.
        /// </summary>
        internal static string CAP_LBL_EMP_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_EMP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 员工姓名.
        /// </summary>
        internal static string CAP_LBL_EMP_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_EMP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工号.
        /// </summary>
        internal static string CAP_LBL_EMP_NO {
            get {
                return ResourceManager.GetString("CAP_LBL_EMP_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期.
        /// </summary>
        internal static string CAP_LBL_ENTRY_DATE {
            get {
                return ResourceManager.GetString("CAP_LBL_ENTRY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分机.
        /// </summary>
        internal static string CAP_LBL_EXT {
            get {
                return ResourceManager.GetString("CAP_LBL_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分机号.
        /// </summary>
        internal static string CAP_LBL_EXT_NO {
            get {
                return ResourceManager.GetString("CAP_LBL_EXT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附件名.
        /// </summary>
        internal static string CAP_LBL_FILE_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能 ID.
        /// </summary>
        internal static string CAP_LBL_FUNC_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_FUNC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P--弹出新窗口.
        /// </summary>
        internal static string CAP_LBL_HEADLINK_PUPOP {
            get {
                return ResourceManager.GetString("CAP_LBL_HEADLINK_PUPOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L--本窗口打开.
        /// </summary>
        internal static string CAP_LBL_HEADLINK_SELF {
            get {
                return ResourceManager.GetString("CAP_LBL_HEADLINK_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统保护.
        /// </summary>
        internal static string CAP_LBL_IS_SYS {
            get {
                return ResourceManager.GetString("CAP_LBL_IS_SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 职能描述.
        /// </summary>
        internal static string CAP_LBL_JOB_DESC {
            get {
                return ResourceManager.GetString("CAP_LBL_JOB_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件.
        /// </summary>
        internal static string CAP_LBL_KEY {
            get {
                return ResourceManager.GetString("CAP_LBL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接类型.
        /// </summary>
        internal static string CAP_LBL_LINKTYPE {
            get {
                return ResourceManager.GetString("CAP_LBL_LINKTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        internal static string CAP_LBL_LOGIN_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_LOGIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件地址.
        /// </summary>
        internal static string CAP_LBL_MAIL_ACCOUNT {
            get {
                return ResourceManager.GetString("CAP_LBL_MAIL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块.
        /// </summary>
        internal static string CAP_LBL_MODULE {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块 ID.
        /// </summary>
        internal static string CAP_LBL_MODULE_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块.
        /// </summary>
        internal static string CAP_LBL_MODULE_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块 SC.
        /// </summary>
        internal static string CAP_LBL_MODULE_NAME_SC {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE_NAME_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块 TC.
        /// </summary>
        internal static string CAP_LBL_MODULE_NAME_TC {
            get {
                return ResourceManager.GetString("CAP_LBL_MODULE_NAME_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string CAP_LBL_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导航菜单.
        /// </summary>
        internal static string CAP_LBL_NAVIGATING {
            get {
                return ResourceManager.GetString("CAP_LBL_NAVIGATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        internal static string CAP_LBL_ORDER {
            get {
                return ResourceManager.GetString("CAP_LBL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父模块 ID.
        /// </summary>
        internal static string CAP_LBL_PARENT_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_PARENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父模块.
        /// </summary>
        internal static string CAP_LBL_PARENT_MODULE {
            get {
                return ResourceManager.GetString("CAP_LBL_PARENT_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父模块.
        /// </summary>
        internal static string CAP_LBL_PARENT_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_PARENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        internal static string CAP_LBL_PASS_WORD {
            get {
                return ResourceManager.GetString("CAP_LBL_PASS_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        internal static string CAP_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("CAP_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果.
        /// </summary>
        internal static string CAP_LBL_RESULT {
            get {
                return ResourceManager.GetString("CAP_LBL_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色.
        /// </summary>
        internal static string CAP_LBL_ROLE {
            get {
                return ResourceManager.GetString("CAP_LBL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色 ID.
        /// </summary>
        internal static string CAP_LBL_ROLE_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_ROLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色名称.
        /// </summary>
        internal static string CAP_LBL_ROLE_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string CAP_LBL_SITE {
            get {
                return ResourceManager.GetString("CAP_LBL_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区域厂别.
        /// </summary>
        internal static string CAP_LBL_SITE_CODE {
            get {
                return ResourceManager.GetString("CAP_LBL_SITE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子系統.
        /// </summary>
        internal static string CAP_LBL_SUB_SYS_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_SUB_SYS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清理NPM中垃圾表单.
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_CLEAN_FORM {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_CLEAN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INV表单和FlowER表单状态.
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_SYNC_INV {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_SYNC_INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 料号申请单和FlowER表单状态.
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_SYNC_ITEM {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_SYNC_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACN表单和FlowER表单状态.
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_SYNC_PACN {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_SYNC_PACN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步表单状态.
        /// </summary>
        internal static string CAP_LBL_SYS_ADMIN_SYNC_STATUS {
            get {
                return ResourceManager.GetString("CAP_LBL_SYS_ADMIN_SYNC_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览本地文件.
        /// </summary>
        internal static string CAP_LBL_UPLOAD_BROWSE {
            get {
                return ResourceManager.GetString("CAP_LBL_UPLOAD_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传时间.
        /// </summary>
        internal static string CAP_LBL_UPLOAD_TIME {
            get {
                return ResourceManager.GetString("CAP_LBL_UPLOAD_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传者.
        /// </summary>
        internal static string CAP_LBL_UPLOADER {
            get {
                return ResourceManager.GetString("CAP_LBL_UPLOADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        internal static string CAP_LBL_USER {
            get {
                return ResourceManager.GetString("CAP_LBL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        internal static string CAP_LBL_USER_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值.
        /// </summary>
        internal static string CAP_LBL_VALUE {
            get {
                return ResourceManager.GetString("CAP_LBL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否有效.
        /// </summary>
        internal static string CAP_TTL_ACTIVE {
            get {
                return ResourceManager.GetString("CAP_TTL_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限--&gt;部门权限设置.
        /// </summary>
        internal static string CAP_TTL_DEPT_MODULE {
            get {
                return ResourceManager.GetString("CAP_TTL_DEPT_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能项设置.
        /// </summary>
        internal static string CAP_TTL_FUNC {
            get {
                return ResourceManager.GetString("CAP_TTL_FUNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部链接设置.
        /// </summary>
        internal static string CAP_TTL_HEADLINK {
            get {
                return ResourceManager.GetString("CAP_TTL_HEADLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部链接编辑.
        /// </summary>
        internal static string CAP_TTL_HEADLINK_EDIT {
            get {
                return ResourceManager.GetString("CAP_TTL_HEADLINK_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导航菜单维护.
        /// </summary>
        internal static string CAP_TTL_LEFTMENU {
            get {
                return ResourceManager.GetString("CAP_TTL_LEFTMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导航菜单编辑.
        /// </summary>
        internal static string CAP_TTL_LEFTMENU_EDIT {
            get {
                return ResourceManager.GetString("CAP_TTL_LEFTMENU_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局参数维护.
        /// </summary>
        internal static string CAP_TTL_PARA {
            get {
                return ResourceManager.GetString("CAP_TTL_PARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局参数编辑.
        /// </summary>
        internal static string CAP_TTL_PARA_EDIT {
            get {
                return ResourceManager.GetString("CAP_TTL_PARA_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限--&gt;权限查询.
        /// </summary>
        internal static string CAP_TTL_PMT_QRY {
            get {
                return ResourceManager.GetString("CAP_TTL_PMT_QRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限--&gt;角色维护.
        /// </summary>
        internal static string CAP_TTL_ROLE {
            get {
                return ResourceManager.GetString("CAP_TTL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限--&gt;角色部门关系.
        /// </summary>
        internal static string CAP_TTL_ROLE_DEPT {
            get {
                return ResourceManager.GetString("CAP_TTL_ROLE_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限--&gt;角色权限设置.
        /// </summary>
        internal static string CAP_TTL_ROLE_MODULE {
            get {
                return ResourceManager.GetString("CAP_TTL_ROLE_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限--&gt;角色用户关系.
        /// </summary>
        internal static string CAP_TTL_ROLE_USER {
            get {
                return ResourceManager.GetString("CAP_TTL_ROLE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模拟用户.
        /// </summary>
        internal static string CAP_TTL_SIMULATE_USER {
            get {
                return ResourceManager.GetString("CAP_TTL_SIMULATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 權限--&gt;Site權限設置.
        /// </summary>
        internal static string CAP_TTL_SITE_MODULE {
            get {
                return ResourceManager.GetString("CAP_TTL_SITE_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPM 系统管理工具.
        /// </summary>
        internal static string CAP_TTL_SYS_ADMIN {
            get {
                return ResourceManager.GetString("CAP_TTL_SYS_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附件上传.
        /// </summary>
        internal static string CAP_TTL_UPLOAD {
            get {
                return ResourceManager.GetString("CAP_TTL_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效.
        /// </summary>
        internal static string CAP_TTL_USER_ACTIVE {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户资料更新.
        /// </summary>
        internal static string CAP_TTL_USER_EDIT {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失效.
        /// </summary>
        internal static string CAP_TTL_USER_INACTIVE {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户维护.
        /// </summary>
        internal static string CAP_TTL_USER_MAINTAIN {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_MAINTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限--&gt;用户权限设置.
        /// </summary>
        internal static string CAP_TTL_USER_MODULE {
            get {
                return ResourceManager.GetString("CAP_TTL_USER_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择用户.
        /// </summary>
        internal static string CAP_TTL_USERSELECTOR {
            get {
                return ResourceManager.GetString("CAP_TTL_USERSELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查系统配置信息.
        /// </summary>
        internal static string CAP_TTL_VALIDATECFG {
            get {
                return ResourceManager.GetString("CAP_TTL_VALIDATECFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问该页时发生错误!.
        /// </summary>
        internal static string MSG_ERR_ACCESS_PAGE {
            get {
                return ResourceManager.GetString("MSG_ERR_ACCESS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尝试新增时发生错误！.
        /// </summary>
        internal static string MSG_ERR_ADD {
            get {
                return ResourceManager.GetString("MSG_ERR_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在生成权限树时发生错误！.
        /// </summary>
        internal static string MSG_ERR_BUILDTREE {
            get {
                return ResourceManager.GetString("MSG_ERR_BUILDTREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您不能删除.
        /// </summary>
        internal static string MSG_ERR_CANT_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_CANT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您不能编辑.
        /// </summary>
        internal static string MSG_ERR_CANT_EDIT {
            get {
                return ResourceManager.GetString("MSG_ERR_CANT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父结点不能是自身。.
        /// </summary>
        internal static string MSG_ERR_CANT_SAMEAS {
            get {
                return ResourceManager.GetString("MSG_ERR_CANT_SAMEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您输入的模块 ID不能和系统ID相同。.
        /// </summary>
        internal static string MSG_ERR_CANT_SAMEAS_SYSTEM {
            get {
                return ResourceManager.GetString("MSG_ERR_CANT_SAMEAS_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不正确的配置：SYSTEM_ID在配置信息中不存在！.
        /// </summary>
        internal static string MSG_ERR_CFG_SYSID {
            get {
                return ResourceManager.GetString("MSG_ERR_CFG_SYSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证失败，请检查用户名和密码是否正确！.
        /// </summary>
        internal static string MSG_ERR_CHECK_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_ERR_CHECK_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行数据库操作时发生错误。 \\r\\n\\r\\n描述: .
        /// </summary>
        internal static string MSG_ERR_DB_EXEC {
            get {
                return ResourceManager.GetString("MSG_ERR_DB_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尝试删除时发生错误！.
        /// </summary>
        internal static string MSG_ERR_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您选择的项包括其子结点都已被成功删除！.
        /// </summary>
        internal static string MSG_ERR_DELETE_ALL_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE_ALL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败！.
        /// </summary>
        internal static string MSG_ERR_DELETE_FAILED {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您没有选择要删除的项！.
        /// </summary>
        internal static string MSG_ERR_DELETE_NO_ITEM {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE_NO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择的项已被删除！.
        /// </summary>
        internal static string MSG_ERR_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误：.
        /// </summary>
        internal static string MSG_ERR_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择网址!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_ADDRESS {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择参数名称！.
        /// </summary>
        internal static string MSG_ERR_FILLIN_CFG_NAME {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_CFG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择参数值！.
        /// </summary>
        internal static string MSG_ERR_FILLIN_CFG_VALUE {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_CFG_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择部门！.
        /// </summary>
        internal static string MSG_ERR_FILLIN_DEPT {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择名称!.
        /// </summary>
        internal static string MSG_ERR_FILLIN_DISP_NAME {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_DISP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择模块名称。.
        /// </summary>
        internal static string MSG_ERR_FILLIN_MOD {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择顺序号。.
        /// </summary>
        internal static string MSG_ERR_FILLIN_ORDER {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择父模块。.
        /// </summary>
        internal static string MSG_ERR_FILLIN_PMOD {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_PMOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择角色。.
        /// </summary>
        internal static string MSG_ERR_FILLIN_ROLE {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇子系統！.
        /// </summary>
        internal static string MSG_ERR_FILLIN_SUBSYS {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_SUBSYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择用户。.
        /// </summary>
        internal static string MSG_ERR_FILLIN_USER {
            get {
                return ResourceManager.GetString("MSG_ERR_FILLIN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入/选择模块ID。.
        /// </summary>
        internal static string MSG_ERR_FLILLIN_MODID {
            get {
                return ResourceManager.GetString("MSG_ERR_FLILLIN_MODID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除FlowER表单时发生错误！.
        /// </summary>
        internal static string MSG_ERR_FLOWER_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销表单时发生错误！.
        /// </summary>
        internal static string MSG_ERR_FLOWER_DELFORM {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_DELFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 向FlowER送签表单时发生错误！.
        /// </summary>
        internal static string MSG_ERR_FLOWER_SEND_FAIL {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_SEND_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送签时发生错误！.
        /// </summary>
        internal static string MSG_ERR_FLOWER_SENDFORM {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_SENDFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除功能项不成功，\\r\\n描述： .
        /// </summary>
        internal static string MSG_ERR_FUNC_FAIL_DEL_FUNC {
            get {
                return ResourceManager.GetString("MSG_ERR_FUNC_FAIL_DEL_FUNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除角色不成功，\\r\\n描述： .
        /// </summary>
        internal static string MSG_ERR_FUNC_FAIL_DEL_ROLE {
            get {
                return ResourceManager.GetString("MSG_ERR_FUNC_FAIL_DEL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能 ID 和 名称 不能为空。.
        /// </summary>
        internal static string MSG_ERR_FUNC_ID_NAME_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_FUNC_ID_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在获取子结点时发生错误！.
        /// </summary>
        internal static string MSG_ERR_GET_SUBITEM {
            get {
                return ResourceManager.GetString("MSG_ERR_GET_SUBITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请升级您的IE浏览器的版本到6或更高！.
        /// </summary>
        internal static string MSG_ERR_IE_VER {
            get {
                return ResourceManager.GetString("MSG_ERR_IE_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该链接已存在于数据库中！.
        /// </summary>
        internal static string MSG_ERR_LINK_EXISTED {
            get {
                return ResourceManager.GetString("MSG_ERR_LINK_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该链接在数据库中不存在！.
        /// </summary>
        internal static string MSG_ERR_LINK_NOTEXISTED {
            get {
                return ResourceManager.GetString("MSG_ERR_LINK_NOTEXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写Log文件时发生错误！.
        /// </summary>
        internal static string MSG_ERR_LOG {
            get {
                return ResourceManager.GetString("MSG_ERR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名不存在.
        /// </summary>
        internal static string MSG_ERR_LOGINNAM_NOTEXISTED {
            get {
                return ResourceManager.GetString("MSG_ERR_LOGINNAM_NOTEXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名不可为空.
        /// </summary>
        internal static string MSG_ERR_LOGINNAME_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_LOGINNAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名已存在.
        /// </summary>
        internal static string MSG_ERR_LOGINNAME_EXISTED {
            get {
                return ResourceManager.GetString("MSG_ERR_LOGINNAME_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误： CONTENT 不能为空值！.
        /// </summary>
        internal static string MSG_ERR_MAIL_ADD_CONTENT {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_ADD_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误： RECEIVER 不能为空值！  .
        /// </summary>
        internal static string MSG_ERR_MAIL_ADD_RECEIVER {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_ADD_RECEIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误： SUBJECT  不能为空值！.
        /// </summary>
        internal static string MSG_ERR_MAIL_ADD_SUBJECT {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_ADD_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件服务的配置不正确！.
        /// </summary>
        internal static string MSG_ERR_MAIL_CONN_SEND {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_CONN_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件地址必须输入.
        /// </summary>
        internal static string MSG_ERR_MAIL_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尝试建立邮件模版时发生错误！.
        /// </summary>
        internal static string MSG_ERR_MAIL_TEMPLATE {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择链接类型！.
        /// </summary>
        internal static string MSG_ERR_MENUTYPE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_MENUTYPE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块ID不能与系统名相同.
        /// </summary>
        internal static string MSG_ERR_MOD_SAMEAS_SYS {
            get {
                return ResourceManager.GetString("MSG_ERR_MOD_SAMEAS_SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您没有权限访问该页！.
        /// </summary>
        internal static string MSG_ERR_NORIGHT {
            get {
                return ResourceManager.GetString("MSG_ERR_NORIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有定义的数据控件可被装载！.
        /// </summary>
        internal static string MSG_ERR_PAGER_NO_CTRL {
            get {
                return ResourceManager.GetString("MSG_ERR_PAGER_NO_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能为空！.
        /// </summary>
        internal static string MSG_ERR_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不正确的密码！.
        /// </summary>
        internal static string MSG_ERR_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("MSG_ERR_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尝试获取用户密码时发生错误！.
        /// </summary>
        internal static string MSG_ERR_PASSWORD_RTV {
            get {
                return ResourceManager.GetString("MSG_ERR_PASSWORD_RTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到指定的属性.
        /// </summary>
        internal static string MSG_ERR_PROPERTY_NOTFOUND {
            get {
                return ResourceManager.GetString("MSG_ERR_PROPERTY_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您不能编辑系统保护的项！.
        /// </summary>
        internal static string MSG_ERR_PROTECTED_ITEM {
            get {
                return ResourceManager.GetString("MSG_ERR_PROTECTED_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成报表失败！.
        /// </summary>
        internal static string MSG_ERR_REPORT_CREATE {
            get {
                return ResourceManager.GetString("MSG_ERR_REPORT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成报表所需的参数不存在，请重新生成报表！.
        /// </summary>
        internal static string MSG_ERR_REPORT_PARAM_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_REPORT_PARAM_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认输入的字符中没有单引号。.
        /// </summary>
        internal static string MSG_ERR_RMV_QUOTO {
            get {
                return ResourceManager.GetString("MSG_ERR_RMV_QUOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色 ID和角色名称不能为空！.
        /// </summary>
        internal static string MSG_ERR_ROLE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_ROLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功！.
        /// </summary>
        internal static string MSG_ERR_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作Cookie时发生错误！.
        /// </summary>
        internal static string MSG_ERR_SET_CK {
            get {
                return ResourceManager.GetString("MSG_ERR_SET_CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该项已存在！.
        /// </summary>
        internal static string MSG_ERR_SETTING_EXIST {
            get {
                return ResourceManager.GetString("MSG_ERR_SETTING_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该项在数据库中不存在！.
        /// </summary>
        internal static string MSG_ERR_SETTING_NOTEXIST {
            get {
                return ResourceManager.GetString("MSG_ERR_SETTING_NOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 短消息开关的状态为关闭，您不能发送短消息！.
        /// </summary>
        internal static string MSG_ERR_SMS_SIWTCH_OFF {
            get {
                return ResourceManager.GetString("MSG_ERR_SMS_SIWTCH_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尝试更新保存时发生错误！.
        /// </summary>
        internal static string MSG_ERR_UPDATE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传文件失败！.
        /// </summary>
        internal static string MSG_ERR_UPLOAD {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误： 参数 p_intSEQ 不能为空值！.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附件已被删除！.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传过程中发生错误： .
        /// </summary>
        internal static string MSG_ERR_UPLOAD_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传附件失败！.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_FAIL {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传的文件最大40兆字节。.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_FILELMT {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_FILELMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在生成附件的HTML代码时发生错误！.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_GENHTML {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_GENHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能定位文件路径！.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_LACATE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_LACATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有选择文件。.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_NOFILE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_NOFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数Type和ID为空，您不能上传文件。.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_NOTYPE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_NOTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附件上传成功！.
        /// </summary>
        internal static string MSG_ERR_UPLOAD_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尝试删除用户时发生错误！ \\r\\n描述: .
        /// </summary>
        internal static string MSG_ERR_USER_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名不能为空！.
        /// </summary>
        internal static string MSG_ERR_USER_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数不能为空值！.
        /// </summary>
        internal static string MSG_ERR_VALUE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_VALUE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML包格式有错误。.
        /// </summary>
        internal static string MSG_ERR_XML_FORMAT {
            get {
                return ResourceManager.GetString("MSG_ERR_XML_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录帐号为FlowER帐号。.
        /// </summary>
        internal static string MSG_TIP_ACTLOGIN {
            get {
                return ResourceManager.GetString("MSG_TIP_ACTLOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选取Language下拉框中的语言项可改变当前语言设置；.
        /// </summary>
        internal static string MSG_TIP_CHGLANG {
            get {
                return ResourceManager.GetString("MSG_TIP_CHGLANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除选中的项吗？.
        /// </summary>
        internal static string MSG_TIP_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_TIP_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在取消 ....
        /// </summary>
        internal static string MSG_TIP_DIV_CANCELLING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_CANCELLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在删除 ....
        /// </summary>
        internal static string MSG_TIP_DIV_DELETING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_DELETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在处理 ....
        /// </summary>
        internal static string MSG_TIP_DIV_LOADING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在处理 ....
        /// </summary>
        internal static string MSG_TIP_DIV_PROCESSING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在保存 ....
        /// </summary>
        internal static string MSG_TIP_DIV_SAVING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在处理 ....
        /// </summary>
        internal static string MSG_TIP_DIV_WORKING {
            get {
                return ResourceManager.GetString("MSG_TIP_DIV_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        internal static string MSG_TIP_FIRST_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_FIRST_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将密码送到您的邮箱.
        /// </summary>
        internal static string MSG_TIP_GET_PWD {
            get {
                return ResourceManager.GetString("MSG_TIP_GET_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转到该页.
        /// </summary>
        internal static string MSG_TIP_GOTO_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_GOTO_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您好 .
        /// </summary>
        internal static string MSG_TIP_HELLO {
            get {
                return ResourceManager.GetString("MSG_TIP_HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问次数:.
        /// </summary>
        internal static string MSG_TIP_HITCOUNT {
            get {
                return ResourceManager.GetString("MSG_TIP_HITCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最后一页.
        /// </summary>
        internal static string MSG_TIP_LAST_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_LAST_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        internal static string MSG_TIP_NEXT_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_NEXT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前页/页数.
        /// </summary>
        internal static string MSG_TIP_PAGE_TIP {
            get {
                return ResourceManager.GetString("MSG_TIP_PAGE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页 {0} 共 {1}.
        /// </summary>
        internal static string MSG_TIP_PAGER_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_PAGER_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每页显示的记录数.
        /// </summary>
        internal static string MSG_TIP_PAGER_REC_PER_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_PAGER_REC_PER_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的密码已发送到您的邮箱中了。.
        /// </summary>
        internal static string MSG_TIP_PASSWORD_MAIL {
            get {
                return ResourceManager.GetString("MSG_TIP_PASSWORD_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        internal static string MSG_TIP_PREV_PAGE {
            get {
                return ResourceManager.GetString("MSG_TIP_PREV_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用Windows帐号进入系统.
        /// </summary>
        internal static string MSG_TIP_REFRESH {
            get {
                return ResourceManager.GetString("MSG_TIP_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示: .
        /// </summary>
        internal static string MSG_TIP_TIPS {
            get {
                return ResourceManager.GetString("MSG_TIP_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总记录：{0}.
        /// </summary>
        internal static string MSG_TIP_TOTAL_RECORD {
            get {
                return ResourceManager.GetString("MSG_TIP_TOTAL_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示： 您可以输入部门代码或用户名来查找数据。.
        /// </summary>
        internal static string MSG_TIP_USER_SELECTOR {
            get {
                return ResourceManager.GetString("MSG_TIP_USER_SELECTOR", resourceCulture);
            }
        }
    }
}
